In [11]:
import pandas as pd

In [13]:
#merge operation perform based on common column
#join operation perform based on index

In [15]:
#join
df1 = pd.DataFrame({'key1':[1,2,4,5,6],
                      'key2':[4,5,6,7,8],
                      'key3':[3,4,5,6,6]
})

In [17]:
df2 =  pd.DataFrame({'key1':[1,2,45,6,67],
                      'key4':[56,5,6,7,8],
                      'key5':[3,56,5,6,6]
}
)

In [19]:
df1,df2

(   key1  key2  key3
 0     1     4     3
 1     2     5     4
 2     4     6     5
 3     5     7     6
 4     6     8     6,
    key1  key4  key5
 0     1    56     3
 1     2     5    56
 2    45     6     5
 3     6     7     6
 4    67     8     6)

In [21]:
pd.merge(df1, df2, how = 'inner')

   key1  key2  key3  key4  key5
0     1     4     3    56     3
1     2     5     4     5    56
2     6     8     6     7     6

In [23]:
pd.merge(df1,df2,how='left')

   key1  key2  key3  key4  key5
0     1     4     3  56.0   3.0
1     2     5     4   5.0  56.0
2     4     6     5   NaN   NaN
3     5     7     6   NaN   NaN
4     6     8     6   7.0   6.0

In [25]:
pd.merge(df1,df2,how='right')

   key1  key2  key3  key4  key5
0     1   4.0   3.0    56     3
1     2   5.0   4.0     5    56
2    45   NaN   NaN     6     5
3     6   8.0   6.0     7     6
4    67   NaN   NaN     8     6

In [27]:
pd.merge(df1,df2,how='outer')

   key1  key2  key3  key4  key5
0     1   4.0   3.0  56.0   3.0
1     2   5.0   4.0   5.0  56.0
2     4   6.0   5.0   NaN   NaN
3     5   7.0   6.0   NaN   NaN
4     6   8.0   6.0   7.0   6.0
5    45   NaN   NaN   6.0   5.0
6    67   NaN   NaN   8.0   6.0

In [29]:
pd.merge(df1,df2,how='cross')

    key1_x  key2  key3  key1_y  key4  key5
0        1     4     3       1    56     3
1        1     4     3       2     5    56
2        1     4     3      45     6     5
3        1     4     3       6     7     6
4        1     4     3      67     8     6
5        2     5     4       1    56     3
6        2     5     4       2     5    56
7        2     5     4      45     6     5
8        2     5     4       6     7     6
9        2     5     4      67     8     6
10       4     6     5       1    56     3
11       4     6     5       2     5    56
12       4     6     5      45     6     5
13       4     6     5       6     7     6
14       4     6     5      67     8     6
15       5     7     6       1    56     3
16       5     7     6       2     5    56
17       5     7     6      45     6     5
18       5     7     6       6     7     6
19       5     7     6      67     8     6
20       6     8     6       1    56     3
21       6     8     6       2     5    56
22       6     8     6      45     6     5
23       6     8     6       6     7     6
24       6     8     6      67     8     6

In [31]:
df1,df2

(   key1  key2  key3
 0     1     4     3
 1     2     5     4
 2     4     6     5
 3     5     7     6
 4     6     8     6,
    key1  key4  key5
 0     1    56     3
 1     2     5    56
 2    45     6     5
 3     6     7     6
 4    67     8     6)

In [33]:
pd.merge(df1,df2,how='right',left_on='key3',right_on='key5')

   key1_x  key2  key3  key1_y  key4  key5
0     1.0   4.0   3.0       1    56     3
1     NaN   NaN   NaN       2     5    56
2     4.0   6.0   5.0      45     6     5
3     5.0   7.0   6.0       6     7     6
4     6.0   8.0   6.0       6     7     6
5     5.0   7.0   6.0      67     8     6
6     6.0   8.0   6.0      67     8     6

In [35]:
#join
df1 = pd.DataFrame({'key1':[1,2,4,5,6],
                      'key2':[4,5,6,7,8],
                      'key3':[3,4,5,6,6]},
                    index = ['a', 'b', 'c', 'd', 'e']
)

In [37]:
df2 =  pd.DataFrame({'key6':[1,2,45,6,67],
                      'key4':[56,5,6,7,8],
                      'key5':[3,56,5,6,6]
},
index = ['a', 'b', 'h', 'i', 'j']
)

In [39]:
df1.join(df2,how='outer')

   key1  key2  key3  key6  key4  key5
a   1.0   4.0   3.0   1.0  56.0   3.0
b   2.0   5.0   4.0   2.0   5.0  56.0
c   4.0   6.0   5.0   NaN   NaN   NaN
d   5.0   7.0   6.0   NaN   NaN   NaN
e   6.0   8.0   6.0   NaN   NaN   NaN
h   NaN   NaN   NaN  45.0   6.0   5.0
i   NaN   NaN   NaN   6.0   7.0   6.0
j   NaN   NaN   NaN  67.0   8.0   6.0

In [41]:
df1.join(df2,how='inner')

   key1  key2  key3  key6  key4  key5
a     1     4     3     1    56     3
b     2     5     4     2     5    56

In [43]:
df1.join(df2,how='left')

   key1  key2  key3  key6  key4  key5
a     1     4     3   1.0  56.0   3.0
b     2     5     4   2.0   5.0  56.0
c     4     6     5   NaN   NaN   NaN
d     5     7     6   NaN   NaN   NaN
e     6     8     6   NaN   NaN   NaN

In [45]:
df1.join(df2,how='right')

   key1  key2  key3  key6  key4  key5
a   1.0   4.0   3.0     1    56     3
b   2.0   5.0   4.0     2     5    56
h   NaN   NaN   NaN    45     6     5
i   NaN   NaN   NaN     6     7     6
j   NaN   NaN   NaN    67     8     6

In [47]:
df=pd.read_csv(r"C:\Users\mohda\Downloads\titanic (1).csv")

In [49]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [51]:

df.Fare

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [53]:
df['far_inr']=df['Fare'].apply(lambda x: x*92)

In [55]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,far_inr
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,667.0000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,6558.0636
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,729.1000
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4885.2000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,740.6000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1196.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2760.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2157.4000
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2760.0000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,713.0000

In [57]:
df['Name'].apply(len)

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [76]:
df['Flag']=df['Fare'].apply(create_flag)

In [78]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,far_inr,Fare_new,Flag
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,667.0000,674.2500,cheap
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,6558.0636,6629.3469,medium
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,729.1000,737.0250,cheap
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4885.2000,4938.3000,medium
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,740.6000,748.6500,cheap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1196.0000,1209.0000,medium
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2760.0000,2790.0000,medium
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2157.4000,2180.8500,medium
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2760.0000,2790.0000,medium
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,713.0000,720.7500,cheap

In [74]:
def create_flag(x):
    if x<10:
        return "cheap"
    elif x>10 and x<90:
        return "medium"
    else:
        return "high"

In [81]:
data = {"a": [1, 2, 3, 4],
       "b": [5, 5, 6, 7],
       "c": ["pw", "skills", "aj", "cj"]}
df1 = pd.DataFrame(data)

In [83]:
df1

   a  b       c
0  1  5      pw
1  2  5  skills
2  3  6      aj
3  4  7      cj

In [85]:
df1.set_index('c',inplace=True)

In [87]:
df1

        a  b
c
pw      1  5
skills  2  5
aj      3  6
cj      4  7

In [89]:
df1.reset_index(drop=True,inplace=True)

In [91]:
df1

   a  b
0  1  5
1  2  5
2  3  6
3  4  7

In [93]:
df1.reindex(['a','b','c','d'])

    a   b
a NaN NaN
b NaN NaN
c NaN NaN
d NaN NaN

In [ ]:
df1.reindex([0,1,3,2])

In [105]:
for i in df1.iterrows(): 
    print(i,"---------------")

(0, a    1
b    5
Name: 0, dtype: int64) ---------------
(1, a    2
b    5
Name: 1, dtype: int64) ---------------
(2, a    3
b    6
Name: 2, dtype: int64) ---------------
(3, a    4
b    7
Name: 3, dtype: int64) ---------------

In [107]:
for i in df1.items():  #column wise
    print(i)

('a', 0    1
1    2
2    3
3    4
Name: a, dtype: int64)
('b', 0    5
1    5
2    6
3    7
Name: b, dtype: int64)

In [109]:
def add(x):
    return x.sum()

In [117]:
df1

   a  b
0  1  5
1  2  5
2  3  6
3  4  7

In [121]:
df1.apply(add,axis=0)

a    10
b    23
dtype: int64

In [123]:
df1.apply(add,axis=1)

0     6
1     7
2     9
3    11
dtype: int64

In [125]:
df1.applymap(lambda x:x**2) #this method for dataframe

C:\Users\mohda\AppData\Local\Temp\ipykernel_19868\231730792.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda x:x**2)

    a   b
0   1  25
1   4  25
2   9  36
3  16  49

In [127]:
df1.sort_values(by='a')

   a  b
0  1  5
1  2  5
2  3  6
3  4  7