In [5]:
import pandas as pd

In [7]:
df=pd.read_csv(r"C:\Users\mohda\Downloads\taxonomy.csv")

In [9]:
df

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [11]:
df.columns

Index(['taxonomy_id', 'name', 'parent_id', 'parent_name'], dtype='object')

In [13]:
df.head()

  taxonomy_id                     name parent_id     parent_name
0         101                Emergency       NaN             NaN
1      101-01        Disaster Response       101       Emergency
2      101-02           Emergency Cash       101       Emergency
3   101-02-01        Help Pay for Food    101-02  Emergency Cash
4   101-02-02  Help Pay for Healthcare    101-02  Emergency Cash

In [15]:
df.tail()

    taxonomy_id                          name parent_id           parent_name
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

In [17]:
df.dtypes

taxonomy_id    object
name           object
parent_id      object
parent_name    object
dtype: object

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290 entries, 0 to 289
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   taxonomy_id  290 non-null    object
 1   name         290 non-null    object
 2   parent_id    279 non-null    object
 3   parent_name  279 non-null    object
dtypes: object(4)
memory usage: 9.2+ KB

In [21]:
df.describe()

       taxonomy_id          name  parent_id       parent_name
count          290           290        279               279
unique         290           183         60                50
top            101  Nursing Home  106-06-07  Health Education
freq             1             4         11                15

In [23]:
df=pd.read_csv(r"C:\Users\mohda\Downloads\titanic (1).csv")

In [25]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [27]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [29]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [33]:
df.describe()   #statiscally measure

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [35]:
df[['PassengerId','Pclass','SibSp']]  #subset

     PassengerId  Pclass  SibSp
0              1       3      1
1              2       1      1
2              3       3      0
3              4       1      1
4              5       3      0
..           ...     ...    ...
886          887       2      0
887          888       1      0
888          889       3      1
889          890       1      0
890          891       3      0

[891 rows x 3 columns]

In [37]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [39]:
[df.dtypes=='object']

[PassengerId    False
 Survived       False
 Pclass         False
 Name            True
 Sex             True
 Age            False
 SibSp          False
 Parch          False
 Ticket          True
 Fare           False
 Cabin           True
 Embarked        True
 dtype: bool]

In [41]:
df.dtypes[df.dtypes=='object']

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [43]:
df.dtypes[df.dtypes=='object'].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [45]:
df[df.dtypes[df.dtypes=='object'].index]

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [33]:
df[df.dtypes[df.dtypes!='object'].index].describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [35]:
df.describe(include='object')

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [37]:
df.describe(include='all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,B96 B98,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [39]:
df.describe()  #five point summary min,25%,50%,75%,max

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [41]:
df.astype('object').describe()  #statistical

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891,891,891,891,891,714.0,891,891,891,891.00,204,889
unique,891,2,3,891,2,88.0,7,7,681,248.00,147,3
top,1,0,3,"Braund, Mr. Owen Harris",male,24.0,0,0,347082,8.05,B96 B98,S
freq,1,549,491,1,577,30.0,608,678,7,43.00,4,644

In [43]:
df[0:100:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.00,1,0,A/5 21171,7.2500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.00,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.00,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C
12,13,0,3,"Saundercock, Mr. William Henry",male,20.00,0,0,A/5. 2151,8.0500,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.00,0,0,248706,16.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.00,1,0,345763,18.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.00,0,0,248698,13.0000,D56,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,21.0750,NaN,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.00,0,0,PC 17601,27.7208,NaN,C
33,34,0,2,"Wheadon, Mr. Edward H",male,66.00,0,0,C.A. 24579,10.5000,NaN,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C
42,43,0,3,"Kraeff, Mr. Theodor",male,NaN,0,0,349253,7.8958,NaN,C
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN,S
48,49,0,3,"Samaan, Mr. Youssef",male,NaN,2,0,2662,21.6792,NaN,C
51,52,0,3,"Nosworthy, Mr. Richard Cater",male,21.00,0,0,A/4. 39886,7.8000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.00,0,1,113509,61.9792,B30,C
57,58,0,3,"Novel, Mr. Mansouer",male,28.50,0,0,2697,7.2292,NaN,C
60,61,0,3,"Sirayanian, Mr. Orsen",male,22.00,0,0,2669,7.2292,NaN,C
63,64,0,3,"Skoog, Master. Harald",male,4.00,3,2,347088,27.9000,NaN,S
66,67,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29.00,0,0,C.A. 29395,10.5000,F33,S
69,70,0,3,"Kink, Mr. Vincenz",male,26.00,2,0,315151,8.6625,NaN,S
72,73,0,2,"Hood, Mr. Ambrose Jr",male,21.00,0,0,S.O.C. 14879,73.5000,NaN,S
75,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.00,0,0,348123,7.6500,F G73,S
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
81,82,1,3,"Sheerlinck, Mr. Jan Baptist",male,29.00,0,0,345779,9.5000,NaN,S
84,85,1,2,"Ilett, Miss. Bertha",female,17.00,0,0,SO/C 14885,10.5000,NaN,S
87,88,0,3,"Slocovski, Mr. Selman Francis",male,NaN,0,0,SOTON/OQ 392086,8.0500,NaN,S
90,91,0,3,"Christmann, Mr. Emil",male,29.00,0,0,343276,8.0500,NaN,S
93,94,0,3,"Dean, Mr. Bertram Frank",male,26.00,1,2,C.A. 2315,20.5750,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.00,0,0,PC 17754,34.6542,A5,C
99,100,0,2,"Kantor, Mr. Sinai",male,34.00,1,0,244367,26.0000,NaN,S

In [47]:
df['death']=100

In [48]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,100
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,100
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,100
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,100
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,100
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,100
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,100
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,100
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,100

In [51]:
df['new_column']='new_join'

In [53]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,100,new_join
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,100,new_join
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,100,new_join
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,100,new_join
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,100,new_join
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,100,new_join
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,100,new_join
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,100,new_join
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,100,new_join
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,100,new_join

In [57]:
df['add']= df['SibSp']+df['Parch']  #string not add witrh int

In [59]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column,add
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,100,new_join,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,100,new_join,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,100,new_join,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,100,new_join,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,100,new_join,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,100,new_join,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,100,new_join,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,100,new_join,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,100,new_join,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,100,new_join,0

In [69]:
df['addition']=df['new_column']+ df['Name']  #string add strings

In [71]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column,add,addition
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,100,new_join,1,"new_joinBraund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,100,new_join,1,"new_joinCumings, Mrs. John Bradley (Florence B..."
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,100,new_join,0,"new_joinHeikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,100,new_join,1,"new_joinFutrelle, Mrs. Jacques Heath (Lily May..."
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,100,new_join,0,"new_joinAllen, Mr. William Henry"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,100,new_join,0,"new_joinMontvila, Rev. Juozas"
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,100,new_join,0,"new_joinGraham, Miss. Margaret Edith"
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,100,new_join,3,"new_joinJohnston, Miss. Catherine Helen ""Carrie"""
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,100,new_join,0,"new_joinBehr, Mr. Karl Howell"
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,100,new_join,0,"new_joinDooley, Mr. Patrick"

In [75]:
pd.Categorical(df['Parch'])

[0, 0, 0, 0, 0, ..., 0, 0, 2, 0, 0]
Length: 891
Categories (7, int64): [0, 1, 2, 3, 4, 5, 6]

In [77]:
pd.Categorical(df['Cabin'])

[NaN, 'C85', NaN, 'C123', NaN, ..., NaN, 'B42', NaN, 'C148', NaN]
Length: 891
Categories (147, object): ['A10', 'A14', 'A16', 'A19', ..., 'F38', 'F4', 'G6', 'T']

In [83]:
df['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [85]:
df['Cabin'].nunique()

147

In [89]:
df['Cabin'].value_counts()

Cabin
B96 B98        4
G6             4
C23 C25 C27    4
C22 C26        3
F33            3
              ..
E34            1
C7             1
C54            1
E36            1
C148           1
Name: count, Length: 147, dtype: int64

In [91]:
pd.Categorical(df['Ticket'])

['A/5 21171', 'PC 17599', 'STON/O2. 3101282', '113803', '373450', ..., '211536', '112053', 'W./C. 6607', '111369', '370376']
Length: 891
Categories (681, object): ['110152', '110413', '110465', '110564', ..., 'W./C. 6609', 'W.E.P. 5734', 'W/C 14208', 'WE/P 5735']

In [93]:
df['Ticket'].unique()

array(['A/5 21171', 'PC 17599', 'STON/O2. 3101282', '113803', '373450',
       '330877', '17463', '349909', '347742', '237736', 'PP 9549',
       '113783', 'A/5. 2151', '347082', '350406', '248706', '382652',
       '244373', '345763', '2649', '239865', '248698', '330923', '113788',
       '347077', '2631', '19950', '330959', '349216', 'PC 17601',
       'PC 17569', '335677', 'C.A. 24579', 'PC 17604', '113789', '2677',
       'A./5. 2152', '345764', '2651', '7546', '11668', '349253',
       'SC/Paris 2123', '330958', 'S.C./A.4. 23567', '370371', '14311',
       '2662', '349237', '3101295', 'A/4. 39886', 'PC 17572', '2926',
       '113509', '19947', 'C.A. 31026', '2697', 'C.A. 34651', 'CA 2144',
       '2669', '113572', '36973', '347088', 'PC 17605', '2661',
       'C.A. 29395', 'S.P. 3464', '3101281', '315151', 'C.A. 33111',
       'S.O.C. 14879', '2680', '1601', '348123', '349208', '374746',
       '248738', '364516', '345767', '345779', '330932', '113059',
       'SO/C 14885', '3101278', 'W./C. 6608', 'SOTON/OQ 392086', '343275',
       '343276', '347466', 'W.E.P. 5734', 'C.A. 2315', '364500', '374910',
       'PC 17754', 'PC 17759', '231919', '244367', '349245', '349215',
       '35281', '7540', '3101276', '349207', '343120', '312991', '349249',
       '371110', '110465', '2665', '324669', '4136', '2627',
       'STON/O 2. 3101294', '370369', 'PC 17558', 'A4. 54510', '27267',
       '370372', 'C 17369', '2668', '347061', '349241',
       'SOTON/O.Q. 3101307', 'A/5. 3337', '228414', 'C.A. 29178',
       'SC/PARIS 2133', '11752', '7534', 'PC 17593', '2678', '347081',
       'STON/O2. 3101279', '365222', '231945', 'C.A. 33112', '350043',
       '230080', '244310', 'S.O.P. 1166', '113776', 'A.5. 11206',
       'A/5. 851', 'Fa 265302', 'PC 17597', '35851', 'SOTON/OQ 392090',
       '315037', 'CA. 2343', '371362', 'C.A. 33595', '347068', '315093',
       '363291', '113505', 'PC 17318', '111240', 'STON/O 2. 3101280',
       '17764', '350404', '4133', 'PC 17595', '250653', 'LINE',
       'SC/PARIS 2131', '230136', '315153', '113767', '370365', '111428',
       '364849', '349247', '234604', '28424', '350046', 'PC 17610',
       '368703', '4579', '370370', '248747', '345770', '3101264', '2628',
       'A/5 3540', '347054', '2699', '367231', '112277',
       'SOTON/O.Q. 3101311', 'F.C.C. 13528', 'A/5 21174', '250646',
       '367229', '35273', 'STON/O2. 3101283', '243847', '11813',
       'W/C 14208', 'SOTON/OQ 392089', '220367', '21440', '349234',
       '19943', 'PP 4348', 'SW/PP 751', 'A/5 21173', '236171', '347067',
       '237442', 'C.A. 29566', 'W./C. 6609', '26707', 'C.A. 31921',
       '28665', 'SCO/W 1585', '367230', 'W./C. 14263',
       'STON/O 2. 3101275', '2694', '19928', '347071', '250649', '11751',
       '244252', '362316', '113514', 'A/5. 3336', '370129', '2650',
       'PC 17585', '110152', 'PC 17755', '230433', '384461', '110413',
       '112059', '382649', 'C.A. 17248', '347083', 'PC 17582', 'PC 17760',
       '113798', '250644', 'PC 17596', '370375', '13502', '347073',
       '239853', 'C.A. 2673', '336439', '347464', '345778', 'A/5. 10482',
       '113056', '349239', '345774', '349206', '237798', '370373',
       '19877', '11967', 'SC/Paris 2163', '349236', '349233', 'PC 17612',
       '2693', '113781', '19988', '9234', '367226', '226593', 'A/5 2466',
       '17421', 'PC 17758', 'P/PP 3381', 'PC 17485', '11767', 'PC 17608',
       '250651', '349243', 'F.C.C. 13529', '347470', '29011', '36928',
       '16966', 'A/5 21172', '349219', '234818', '345364', '28551',
       '111361', '113043', 'PC 17611', '349225', '7598', '113784',
       '248740', '244361', '229236', '248733', '31418', '386525',
       'C.A. 37671', '315088', '7267', '113510', '2695', '2647', '345783',
       '237671', '330931', '330980', 'SC/PARIS 2167', '2691',
       'SOTON/O.Q. 3101310', 'C 7076', '110813', '2626', '14313',
       'PC 17477', '11765', '3101267', '323951', 'C 7077', '113503',
       '2648', '347069', 'PC 17757', '2653', 'STON/O 2. 3101293',
       '349227', '27849', '367655', 'SC 1748', '113760', '350034',
       '3101277', '350052', '350407', '28403', '244278', '240929',
       'STON/O 2. 3101289', '341826', '4137', '315096', '28664', '347064',
       '29106', '312992', '349222', '394140', 'STON/O 2. 3101269',
       '343095', '28220', '250652', '28228', '345773', '349254',
       'A/5. 13032', '315082', '347080', 'A/4. 34244', '2003', '250655',
       '364851', 'SOTON/O.Q. 392078', '110564', '376564', 'SC/AH 3085',
       'STON/O 2. 3101274', '13507', 'C.A. 18723', '345769', '347076',
       '230434', '65306', '33638', '113794', '2666', '113786', '65303',
       '113051', '17453', 'A/5 2817', '349240', '13509', '17464',
       'F.C.C. 13531', '371060', '19952', '364506', '111320', '234360',
       'A/S 2816', 'SOTON/O.Q. 3101306', '113792', '36209', '323592',
       '315089', 'SC/AH Basle 541', '7553', '31027', '3460', '350060',
       '3101298', '239854', 'A/5 3594', '4134', '11771', 'A.5. 18509',
       '65304', 'SOTON/OQ 3101317', '113787', 'PC 17609', 'A/4 45380',
       '36947', 'C.A. 6212', '350035', '315086', '364846', '330909',
       '4135', '26360', '111427', 'C 4001', '382651', 'SOTON/OQ 3101316',
       'PC 17473', 'PC 17603', '349209', '36967', 'C.A. 34260', '226875',
       '349242', '12749', '349252', '2624', '2700', '367232',
       'W./C. 14258', 'PC 17483', '3101296', '29104', '2641', '2690',
       '315084', '113050', 'PC 17761', '364498', '13568', 'WE/P 5735',
       '2908', '693', 'SC/PARIS 2146', '244358', '330979', '2620',
       '347085', '113807', '11755', '345572', '372622', '349251',
       '218629', 'SOTON/OQ 392082', 'SOTON/O.Q. 392087', 'A/4 48871',
       '349205', '2686', '350417', 'S.W./PP 752', '11769', 'PC 17474',
       '14312', 'A/4. 20589', '358585', '243880', '2689',
       'STON/O 2. 3101286', '237789', '13049', '3411', '237565', '13567',
       '14973', 'A./5. 3235', 'STON/O 2. 3101273', 'A/5 3902', '364848',
       'SC/AH 29037', '248727', '2664', '349214', '113796', '364511',
       '111426', '349910', '349246', '113804', 'SOTON/O.Q. 3101305',
       '370377', '364512', '220845', '31028', '2659', '11753', '350029',
       '54636', '36963', '219533', '349224', '334912', '27042', '347743',
       '13214', '112052', '237668', 'STON/O 2. 3101292', '350050',
       '349231', '13213', 'S.O./P.P. 751', 'CA. 2314', '349221', '8475',
       '330919', '365226', '349223', '29751', '2623', '5727', '349210',
       'STON/O 2. 3101285', '234686', '312993', 'A/5 3536', '19996',
       '29750', 'F.C. 12750', 'C.A. 24580', '244270', '239856', '349912',
       '342826', '4138', '330935', '6563', '349228', '350036', '24160',
       '17474', '349256', '2672', '113800', '248731', '363592', '35852',
       '348121', 'PC 17475', '36864', '350025', '223596', 'PC 17476',
       'PC 17482', '113028', '7545', '250647', '348124', '34218', '36568',
       '347062', '350048', '12233', '250643', '113806', '315094', '36866',
       '236853', 'STON/O2. 3101271', '239855', '28425', '233639',
       '349201', '349218', '16988', '376566', 'STON/O 2. 3101288',
       '250648', '113773', '335097', '29103', '392096', '345780',
       '349204', '350042', '29108', '363294', 'SOTON/O2 3101272', '2663',
       '347074', '112379', '364850', '8471', '345781', '350047',
       'S.O./P.P. 3', '2674', '29105', '347078', '383121', '36865',
       '2687', '113501', 'W./C. 6607', 'SOTON/O.Q. 3101312', '374887',
       '3101265', '12460', 'PC 17600', '349203', '28213', '17465',
       '349244', '2685', '2625', '347089', '347063', '112050', '347087',
       '248723', '3474', '28206', '364499', '112058', 'STON/O2. 3101290',
       'S.C./PARIS 2079', 'C 7075', '315098', '19972', '368323', '367228',
       '2671', '347468', '2223', 'PC 17756', '315097', '392092', '11774',
       'SOTON/O2 3101287', '2683', '315090', 'C.A. 5547', '349213',
       '347060', 'PC 17592', '392091', '113055', '2629', '350026',
       '28134', '17466', '233866', '236852', 'SC/PARIS 2149', 'PC 17590',
       '345777', '349248', '695', '345765', '2667', '349212', '349217',
       '349257', '7552', 'C.A./SOTON 34068', 'SOTON/OQ 392076', '211536',
       '112053', '111369', '370376'], dtype=object)

In [97]:
df['Ticket'].value_counts()

Ticket
347082      7
CA. 2343    7
1601        7
3101295     6
CA 2144     6
           ..
9234        1
19988       1
2693        1
PC 17612    1
370376      1
Name: count, Length: 681, dtype: int64

In [99]:
df['Age']<5

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [101]:
df[df['Age']<5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column,add,addition
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S,100,new_join,4,"new_joinPalsson, Master. Gosta Leonard"
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S,100,new_join,2,"new_joinSandstrom, Miss. Marguerite Rut"
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q,100,new_join,5,"new_joinRice, Master. Eugene"
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C,100,new_join,3,"new_joinLaroche, Miss. Simonne Marie Anne Andree"
63,64,0,3,"Skoog, Master. Harald",male,4.00,3,2,347088,27.9000,NaN,S,100,new_join,5,"new_joinSkoog, Master. Harald"
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S,100,new_join,2,"new_joinCaldwell, Master. Alden Gates"
119,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S,100,new_join,6,"new_joinAndersson, Miss. Ellis Anna Maria"
164,165,0,3,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,39.6875,NaN,S,100,new_join,5,"new_joinPanula, Master. Eino Viljami"
171,172,0,3,"Rice, Master. Arthur",male,4.00,4,1,382652,29.1250,NaN,Q,100,new_join,5,"new_joinRice, Master. Arthur"
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S,100,new_join,2,"new_joinJohnson, Miss. Eleanor Ileen"
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S,100,new_join,3,"new_joinBecker, Master. Richard F"
184,185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,22.0250,NaN,S,100,new_join,2,"new_joinKink-Heilmann, Miss. Luise Gretchen"
193,194,1,2,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,F2,S,100,new_join,2,"new_joinNavratil, Master. Michel M"
205,206,0,3,"Strom, Miss. Telma Matilda",female,2.00,0,1,347054,10.4625,G6,S,100,new_join,1,"new_joinStrom, Miss. Telma Matilda"
261,262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,NaN,S,100,new_join,6,"new_joinAsplund, Master. Edvin Rojj Felix"
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,100,new_join,3,"new_joinAllison, Miss. Helen Loraine"
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,100,new_join,3,"new_joinAllison, Master. Hudson Trevor"
340,341,1,2,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,F2,S,100,new_join,2,"new_joinNavratil, Master. Edmond Roger"
348,349,1,3,"Coutts, Master. William Loch ""William""",male,3.00,1,1,C.A. 37671,15.9000,NaN,S,100,new_join,2,"new_joinCoutts, Master. William Loch ""William"""
374,375,0,3,"Palsson, Miss. Stina Viola",female,3.00,3,1,349909,21.0750,NaN,S,100,new_join,4,"new_joinPalsson, Miss. Stina Viola"
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.00,0,2,2653,15.7417,NaN,C,100,new_join,2,"new_joinNakid, Miss. Maria (""Mary"")"
386,387,0,3,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,46.9000,NaN,S,100,new_join,7,"new_joinGoodwin, Master. Sidney Leonard"
407,408,1,2,"Richards, Master. William Rowe",male,3.00,1,1,29106,18.7500,NaN,S,100,new_join,2,"new_joinRichards, Master. William Rowe"
445,446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,A34,S,100,new_join,2,"new_joinDodge, Master. Washington"
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C,100,new_join,3,"new_joinBaclini, Miss. Helene Barbara"
479,480,1,3,"Hirvonen, Miss. Hildur E",female,2.00,0,1,3101298,12.2875,NaN,S,100,new_join,1,"new_joinHirvonen, Miss. Hildur E"
530,531,1,2,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,26.0000,NaN,S,100,new_join,2,"new_joinQuick, Miss. Phyllis May"
618,619,1,2,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,39.0000,F4,S,100,new_join,3,"new_joinBecker, Miss. Marion Louise"
642,643,0,3,"Skoog, Miss. Margit Elizabeth",female,2.00,3,2,347088,27.9000,NaN,S,100,new_join,5,"new_joinSkoog, Miss. Margit Elizabeth"
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C,100,new_join,3,"new_joinBaclini, Miss. Eugenie"
691,692,1,3,"Karun, Miss. Manca",female,4.00,0,1,349256,13.4167,NaN,C,100,new_join,1,"new_joinKarun, Miss. Manca"
750,751,1,2,"Wells, Miss. Joan",female,4.00,1,1,29103,23.0000,NaN,S,100,new_join,2,"new_joinWells, Miss. Joan"
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S,100,new_join,2,"new_joinHamalainen, Master. Viljo"
788,789,1,3,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,20.5750,NaN,S,100,new_join,3,"new_joinDean, Master. Bertram Vere"
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C,100,new_join,1,"new_joinThomas, Master. Assad Alexander"
824,825,0,3,"Panula, Master. Urho Abraham",male,2.00,4,1,3101295,39.6875,NaN,S,100,new_join,5,"new_joinPanula, Master. Urho Abraham"
827,828,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,NaN,C,100,new_join,2,"new_joinMallet, Master. Andre"
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S,100,new_join,2,"new_joinRichards, Master. George Sibley"
850,851,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,347082,31.2750,NaN,S,100,new_join,6,"new_joinAndersson, Master. Sigvard Harald Elias"
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S,100,new_join,2,"new_joinJohnson, Master. Harold Theodor"

In [111]:
df['Embarked']='S'

In [113]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column,add,addition
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,100,new_join,1,"new_joinBraund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,S,100,new_join,1,"new_joinCumings, Mrs. John Bradley (Florence B..."
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,100,new_join,0,"new_joinHeikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,100,new_join,1,"new_joinFutrelle, Mrs. Jacques Heath (Lily May..."
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,100,new_join,0,"new_joinAllen, Mr. William Henry"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,100,new_join,0,"new_joinMontvila, Rev. Juozas"
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,100,new_join,0,"new_joinGraham, Miss. Margaret Edith"
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,100,new_join,3,"new_joinJohnston, Miss. Catherine Helen ""Carrie"""
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,S,100,new_join,0,"new_joinBehr, Mr. Karl Howell"
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,S,100,new_join,0,"new_joinDooley, Mr. Patrick"

In [117]:
df[df['PassengerId']<4]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column,add,addition
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,100,new_join,1,"new_joinBraund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,S,100,new_join,1,"new_joinCumings, Mrs. John Bradley (Florence B..."
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,100,new_join,0,"new_joinHeikkinen, Miss. Laina"

In [123]:
df[df['Survived']<3].Age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [125]:
df[df['Survived']<3].Age.value_counts

<bound method IndexOpsMixin.value_counts of 0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64>

In [143]:
df[df['Sex'] == 'female'].Age

1      38.0
2      26.0
3      35.0
8      27.0
9      14.0
       ...
880    25.0
882    22.0
885    39.0
887    19.0
888     NaN
Name: Age, Length: 314, dtype: float64

In [147]:
df[df['Age']>18].Name

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
885                 Rice, Mrs. William (Margaret Norton)
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 575, dtype: object

In [153]:
list(df[df['Age']>18].Name)

['Braund, Mr. Owen Harris',
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
 'Heikkinen, Miss. Laina',
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 'Allen, Mr. William Henry',
 'McCarthy, Mr. Timothy J',
 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
 'Bonnell, Miss. Elizabeth',
 'Saundercock, Mr. William Henry',
 'Andersson, Mr. Anders Johan',
 'Hewlett, Mrs. (Mary D Kingcome) ',
 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
 'Fynney, Mr. Joseph J',
 'Beesley, Mr. Lawrence',
 'Sloper, Mr. William Thompson',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
 'Fortune, Mr. Charles Alexander',
 'Uruchurtu, Don. Manuel E',
 'Wheadon, Mr. Edward H',
 'Meyer, Mr. Edgar Joseph',
 'Holverson, Mr. Alexander Oskar',
 'Cann, Mr. Ernest Charles',
 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
 'Devaney, Miss. Margaret Delia',
 'Nosworthy, Mr. Richard Cater',
 'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
 'Ostby, Mr. Engelhart Cornelius',
 'Rugg, Miss. Emily',
 'Novel, Mr. Mansouer',
 'Sirayanian, Mr. Orsen',
 'Icard, Miss. Amelie',
 'Harris, Mr. Henry Birkhardt',
 'Nye, Mrs. (Elizabeth Ramell)',
 'Crease, Mr. Ernest James',
 'Kink, Mr. Vincenz',
 'Jenkin, Mr. Stephen Curnow',
 'Hood, Mr. Ambrose Jr',
 'Chronopoulos, Mr. Apostolos',
 'Bing, Mr. Lee',
 'Moen, Mr. Sigurd Hansen',
 'Dowdell, Miss. Elizabeth',
 'Waelens, Mr. Achille',
 'Sheerlinck, Mr. Jan Baptist',
 'Carrau, Mr. Francisco M',
 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
 'Fortune, Miss. Mabel Helen',
 'Celotti, Mr. Francesco',
 'Christmann, Mr. Emil',
 'Andreasson, Mr. Paul Edvin',
 'Chaffee, Mr. Herbert Fuller',
 'Dean, Mr. Bertram Frank',
 'Coxon, Mr. Daniel',
 'Goldschmidt, Mr. George B',
 'Greenfield, Mr. William Bertram',
 'Doling, Mrs. John T (Ada Julia Bone)',
 'Kantor, Mr. Sinai',
 'Petranec, Miss. Matilda',
 'White, Mr. Richard Frasar',
 'Johansson, Mr. Gustaf Joel',
 'Gustafsson, Mr. Anders Vilhelm',
 'Mionoff, Mr. Stoytcho',
 'Salkjelsvik, Miss. Anna Kristine',
 'Rekic, Mr. Tido',
 'Porter, Mr. Walter Chamberlain',
 'Barton, Mr. David John',
 'Jussila, Miss. Katriina',
 'Pekoniemi, Mr. Edvard',
 'Connors, Mr. Patrick',
 'Turpin, Mr. William John Robert',
 'Baxter, Mr. Quigg Edmond',
 'Hickman, Mr. Stanley George',
 'Nasser, Mr. Nicholas',
 'Webber, Miss. Susan',
 'White, Mr. Percival Wayland',
 'Madsen, Mr. Fridtjof Arne',
 'Ekstrom, Mr. Johan',
 'Drazenoic, Mr. Jozef',
 'Coelho, Mr. Domingos Fernandeo',
 'Robins, Mrs. Alexander A (Grace Charity Laury)',
 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)',
 'Sobey, Mr. Samuel James Hayden',
 'Richard, Mr. Emile',
 'Newsom, Miss. Helen Monypeny',
 'Futrelle, Mr. Jacques Heath',
 'Giglio, Mr. Victor',
 'Nysten, Miss. Anna Sofia',
 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)',
 'Burke, Mr. Jeremiah',
 'Nicholls, Mr. Joseph Charles',
 'Andersson, Mr. August Edvard ("Wennerstrom")',
 'Navratil, Mr. Michel ("Louis M Hoffman")',
 'Byles, Rev. Thomas Roussel Davids',
 'Bateman, Rev. Robert James',
 'Pears, Mrs. Thomas (Edith Wearne)',
 'Meo, Mr. Alfonzo',
 'van Billiard, Mr. Austin Blyler',
 'Williams, Mr. Charles Duane',
 'Corn, Mr. Harry',
 'Cribb, Mr. John Hatfield',
 'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)',
 'Bengtsson, Mr. John Viktor',
 'Skoog, Mrs. William (Anna Bernhardina Karlsson)',
 'Ling, Mr. Lee',
 'Van der hoef, Mr. Wyckoff',
 'Sivola, Mr. Antti Wilhelm',
 'Smith, Mr. James Clinch',
 'Isham, Miss. Ann Elizabeth',
 'Hale, Mr. Reginald',
 'Leonard, Mr. Lionel',
 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")',
 'Bourke, Mr. John',
 'Turcin, Mr. Stjepan',
 'Pinsky, Mrs. (Rosa)',
 'Carbines, Mr. William',
 'Andersen-Jensen, Miss. Carla Christine Nielsine',
 'Brown, Mrs. James Joseph (Margaret Tobin)',
 'Lurette, Miss. Elise',
 'Olsen, Mr. Karl Siegwart Andreas',
 'Yrois, Miss. Henriette ("Mrs Harbeck")',
 'Vande Walle, Mr. Nestor Cyriel',
 'Johanson, Mr. Jakob Alfred',
 'Youseff, Mr. Gerious',
 'Backstrom, Mr. Karl Alfred',
 'Albimona, Mr. Nassef Cassem',
 'Blank, Mr. Henry',
 'Ali, Mr. Ahmed',
 'Cameron, Miss. Clear Annie',
 'Perkin, Mr. John Henry',
 'Givard, Mr. Hans Kristensen',
 'Newell, Miss. Madeleine',
 'Honkanen, Miss. Eliina',
 'Jacobsohn, Mr. Sidney Samuel',
 'Bazzani, Miss. Albina',
 'Harris, Mr. Walter',
 'Bracken, Mr. James H',
 'Green, Mr. George Henry',
 'Hoyt, Mr. Frederick Maxfield',
 'Berglund, Mr. Karl Ivar Sven',
 'Mellors, Mr. William John',
 'Lovell, Mr. John Hall ("Henry")',
 'Harris, Mrs. Henry Birkhardt (Irene Wallach)',
 'Larsson, Mr. Bengt Edvin',
 'Sjostedt, Mr. Ernst Adolf',
 'Leyson, Mr. Robert William Norman',
 'Hold, Mr. Stephen',
 'Pengelly, Mr. Frederick William',
 'Hunt, Mr. George Henry',
 'Coleridge, Mr. Reginald Charles',
 'Maenpaa, Mr. Matti Alexanteri',
 'Attalah, Mr. Sleiman',
 'Minahan, Dr. William Edward',
 'Lindahl, Miss. Agda Thorilda Viktoria',
 'Hamalainen, Mrs. William (Anna)',
 'Beckwith, Mr. Richard Leonard',
 'Carter, Rev. Ernest Courtenay',
 'Strom, Mrs. Wilhelm (Elna Matilda Persson)',
 'Stead, Mr. William Thomas',
 'Lobb, Mr. William Arthur',
 'Rosblom, Mrs. Viktor (Helena Wilhelmina)',
 'Touma, Mrs. Darwis (Hanne Youssef Razi)',
 'Cherry, Miss. Gladys',
 'Ward, Miss. Anna',
 'Parrish, Mrs. (Lutie Davis)',
 'Taussig, Mr. Emil',
 'Harrison, Mr. William',
 'Reeves, Mr. David',
 'Persson, Mr. Ernst Ulrik',
 'Graham, Mrs. William Thompson (Edith Junkins)',
 'Bissette, Miss. Amelia',
 'Tornquist, Mr. William Henry',
 'Mellinger, Mrs. (Elizabeth Anne Maidment)',
 'Natsch, Mr. Charles H',
 'Andrews, Miss. Kornelia Theodosia',
 'Lindblom, Miss. Augusta Charlotta',
 'Abbott, Mrs. Stanton (Rosa Hunt)',
 'Duane, Mr. Frank',
 'Olsson, Mr. Nils Johan Goransson',
 'Dorking, Mr. Edward Arthur',
 'Stankovic, Mr. Ivan',
 'de Mulder, Mr. Theodore',
 'Naidenoff, Mr. Penko',
 'Hosono, Mr. Masabumi',
 'Connolly, Miss. Kate',
 'Barber, Miss. Ellen "Nellie"',
 'Bishop, Mrs. Dickinson H (Helen Walton)',
 'Levy, Mr. Rene Jacques',
 'Haas, Miss. Aloisia',
 'Mineff, Mr. Ivan',
 'Hanna, Mr. Mansour',
 'Baxter, Mrs. James (Helene DeLaudeniere Chaput)',
 'Johnson, Mr. William Cahoone Jr',
 'Abelson, Mr. Samuel',
 'Francatelli, Miss. Laura Mabel',
 'Hays, Miss. Margaret Bechstein',
 'Lahtinen, Mrs. William (Anna Sylfven)',
 'Hendekovic, Mr. Ignjac',
 'Hart, Mr. Benjamin',
 'Nilsson, Miss. Helmina Josefina',
 'Kantor, Mrs. Sinai (Miriam Sternin)',
 'Moraweck, Dr. Ernest',
 'Wick, Miss. Mary Natalie',
 'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)',
 'Dennis, Mr. Samuel',
 'Danoff, Mr. Yoto',
 'Slayter, Miss. Hilda Mary',
 'Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)',
 'Young, Miss. Marie Grice',
 'Nysveen, Mr. Johan Hansen',
 'Ball, Mrs. (Ada E Hall)',
 'Goldsmith, Mrs. Frank John (Emily Alice Brown)',
 'Partner, Mr. Austen',
 'Graham, Mr. George Edward',
 'Pears, Mr. Thomas Clinton',
 'Burns, Miss. Elizabeth Margaret',
 'Dahl, Mr. Karl Edwart',
 'Blackwell, Mr. Stephen Weart',
 'Fortune, Miss. Alice Elizabeth',
 'Collander, Mr. Erik Gustaf',
 'Sedgwick, Mr. Charles Frederick Waddington',
 'Fox, Mr. Stanley Hubert',
 'Brown, Miss. Amelia "Mildred"',
 'Smith, Miss. Marion Elsie',
 'Dimic, Mr. Jovan',
 'Odahl, Mr. Nils Martin',
 'Arnold-Franchi, Mr. Josef',
 'Vanden Steen, Mr. Leo Peter',
 'Bowerman, Miss. Elsie Edith',
 'Funk, Miss. Annie Clemmer',
 'Skoog, Mr. Wilhelm',
 'del Carlo, Mr. Sebastiano',
 'Barbara, Mrs. (Catherine David)',
 'Asim, Mr. Adola',
 'Adahl, Mr. Mauritz Nils Martin',
 'Warren, Mrs. Frank Manley (Anna Sophia Atkinson)',
 'Aubart, Mme. Leontine Pauline',
 'Harder, Mr. George Achilles',
 'Beavan, Mr. William Thomas',
 'Ringhini, Mr. Sante',
 'Landergren, Miss. Aurora Adelia',
 'Widener, Mr. Harry Elkins',
 'Betros, Mr. Tannous',
 'Gustafsson, Mr. Karl Gideon',
 'Bidois, Miss. Rosalie',
 'Tikkanen, Mr. Juho',
 'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)',
 'Buss, Miss. Kate',
 'Carter, Mr. William Ernest',
 'Jansson, Mr. Carl Olof',
 'Gustafsson, Mr. Johan Birger',
 'Newell, Miss. Marjorie',
 'Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)',
 'Johansson, Mr. Erik',
 'Olsson, Miss. Elina',
 'McKane, Mr. Peter David',
 'Pain, Dr. Alfred',
 'Trout, Mrs. William H (Jessie L)',
 'Niskanen, Mr. Juha',
 'Adams, Mr. John',
 'Jussila, Miss. Mari Aina',
 'Hakkarainen, Mr. Pekka Pietari',
 'Oreskovic, Miss. Marija',
 'Gale, Mr. Shadrach',
 'Widegren, Mr. Carl/Charles Peter',
 'Birkeland, Mr. Hans Martin Monsen',
 'Minahan, Miss. Daisy E',
 'Sundman, Mr. Johan Julian',
 'Drew, Mrs. James Vivian (Lulu Thorne Christian)',
 'Matthews, Mr. William John',
 'Charters, Mr. David',
 'Zimmerman, Mr. Leo',
 'Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)',
 'Clarke, Mrs. Charles V (Ada Maria Winfield)',
 'Phillips, Miss. Kate Florence ("Mrs Kate Louise Phillips Marshall")',
 'Pickard, Mr. Berk (Berk Trembisky)',
 'Bjornstrom-Steffansson, Mr. Mauritz Hakan',
 'Louch, Mrs. Charles Alexander (Alice Adelaide Slow)',
 'Silvey, Mr. William Baird',
 'Ford, Miss. Doolina Margaret "Daisy"',
 'Richards, Mrs. Sidney (Emily Hocking)',
 'Fortune, Mr. Mark',
 'Kvillner, Mr. Johan Henrik Johannesson',
 'Hart, Mrs. Benjamin (Esther Ada Bloomfield)',
 'Hampe, Mr. Leon',
 'Petterson, Mr. Johan Emil',
 'Reynaldo, Ms. Encarnacion',
 'Seward, Mr. Frederic Kimber',
 'Peuchen, Major. Arthur Godfrey',
 'West, Mr. Edwy Arthur',
 'Foreman, Mr. Benjamin Laventall',
 'Goldenberg, Mr. Samuel L',
 'Jalsevac, Mr. Ivan',
 'Millet, Mr. Francis Davis',
 'Toomey, Miss. Ellen',
 'Anderson, Mr. Harry',
 'Morley, Mr. William',
 'Gee, Mr. Arthur H',
 'Milling, Mr. Jacob Christian',
 'Goncalves, Mr. Manuel Estanslas',
 'Smart, Mr. John Montgomery',
 'Cacic, Mr. Luka',
 'West, Mrs. Edwy Arthur (Ada Mary Worth)',
 'Jerwan, Mrs. Amin S (Marie Marthe Thuillard)',
 'Strandberg, Miss. Ida Sofia',
 'Renouf, Mr. Peter Henry',
 'Braund, Mr. Lewis Richard',
 'Karlsson, Mr. Nils August',
 'Rouse, Mr. Richard Henry',
 'Turkula, Mrs. (Hedwig)',
 'Bishop, Mr. Dickinson H',
 'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)',
 'Kent, Mr. Edward Austin',
 'Somerton, Mr. Francis William',
 'Windelov, Mr. Einar',
 'Molson, Mr. Harry Markland',
 'Artagaveytia, Mr. Ramon',
 'Stanley, Mr. Edward Roland',
 'Eustis, Miss. Elizabeth Mussey',
 'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)',
 'Svensson, Mr. Olof',
 'Canavan, Miss. Mary',
 'Laitinen, Miss. Kristina Sofia',
 'Quick, Mrs. Frederick Charles (Jane Richards)',
 'Olsen, Mr. Henry Margido',
 'Lang, Mr. Fang',
 'Daly, Mr. Eugene Patrick',
 'McGough, Mr. James Robert',
 'Rothschild, Mrs. Martin (Elizabeth L. Barrett)',
 'Coleff, Mr. Satio',
 'Walker, Mr. William Anderson',
 'Lemore, Mrs. (Amelia Milley)',
 'Angle, Mrs. William A (Florence "Mary" Agnes Hughes)',
 'Pavlovic, Mr. Stefo',
 'Perreault, Miss. Anne',
 'Vovk, Mr. Janko',
 'Hippach, Mrs. Louis Albert (Ida Sophia Fischer)',
 'Farrell, Mr. James',
 'Ridsdale, Miss. Lucy',
 'Salonen, Mr. Johan Werner',
 'Hocking, Mr. Richard George',
 'Cacic, Miss. Marija',
 'Butt, Major. Archibald Willingham',
 'LeRoy, Miss. Bertha',
 'Frolicher, Miss. Hedwig Margaritha',
 'Crosby, Miss. Harriet R',
 'Beane, Mr. Edward',
 'Douglas, Mr. Walter Donald',
 'Nicholson, Mr. Arthur Ernest',
 'Beane, Mrs. Edward (Ethel Clarke)',
 'Goldsmith, Mr. Frank John',
 'Sharp, Mr. Percival James R',
 'Leeni, Mr. Fahim ("Philip Zenni")',
 'Ohman, Miss. Velin',
 'Wright, Mr. George',
 'Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")',
 'Taussig, Mrs. Emil (Tillie Mandelbaum)',
 'de Messemaeker, Mrs. Guillaume Joseph (Emma)',
 'Sivic, Mr. Husein',
 'Norman, Mr. Robert Douglas',
 'Davies, Mr. Alfred J',
 'Stoytcheff, Mr. Ilia',
 'Palsson, Mrs. Nils (Alma Cornelia Berglund)',
 'Jonsson, Mr. Carl',
 'Harris, Mr. George',
 'Appleton, Mrs. Edward Dale (Charlotte Lamson)',
 'Flynn, Mr. John Irwin ("Irving")',
 'Patchett, Mr. George',
 'Garside, Miss. Ethel',
 'Silvey, Mrs. William Baird (Alice Munger)',
 'Jussila, Mr. Eiriik',
 'Christy, Miss. Julie Rachel',
 'Thayer, Mrs. John Borland (Marian Longstreth Morris)',
 'Downton, Mr. William James',
 'Ross, Mr. John Hugo',
 'Jarvis, Mr. John Denzil',
 'Frolicher-Stehli, Mr. Maxmillian',
 'Gilinski, Mr. Eliezer',
 'Rintamaki, Mr. Matti',
 'Stephenson, Mrs. Walter Bertram (Martha Eustis)',
 'Elsbury, Mr. William James',
 'Chapman, Mr. John Henry',
 'Van Impe, Mr. Jean Baptiste',
 'Johnson, Mr. Alfred',
 'Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")',
 'Jacobsohn, Mrs. Sidney Samuel (Amy Frances Christy)',
 'Torber, Mr. Ernst William',
 'Homer, Mr. Harry ("Mr E Haven")',
 'Lindell, Mr. Edvard Bengtsson',
 'Karaic, Mr. Milan',
 'Daniel, Mr. Robert Williams',
 'Laroche, Mrs. Joseph (Juliette Marie Louise Lafargue)',
 'Shutes, Miss. Elizabeth W',
 'Andersson, Mrs. Anders Johan (Alfrida Konstantia Brogren)',
 'Brocklebank, Mr. William Alfred',
 'Herman, Miss. Alice',
 'Danbom, Mr. Ernst Gilbert',
 'Lobb, Mrs. William Arthur (Cordelia K Stanlick)',
 'Gavey, Mr. Lawrence',
 'Yasbeck, Mr. Antoni',
 'Kimball, Mr. Edwin Nelson Jr',
 'Nakid, Mr. Sahid',
 'Hansen, Mr. Henry Damsgaard',
 'Bowen, Mr. David John "Dai"',
 'Sutton, Mr. Frederick',
 'Kirkland, Rev. Charles Leonard',
 'Longley, Miss. Gretchen Fiske',
 'Bostandyeff, Mr. Guentcho',
 'Barkworth, Mr. Algernon Henry Wilson',
 'Lundahl, Mr. Johan Svensson',
 'Stahelin-Maeglin, Dr. Max',
 'Davis, Miss. Mary',
 'Leinonen, Mr. Antti Gustaf',
 'Collyer, Mr. Harvey',
 'Panula, Mrs. Juha (Maria Emilia Ojala)',
 'Jensen, Mr. Hans Peder',
 'Sagesser, Mlle. Emma',
 'Harper, Mr. Henry Sleeper',
 'Cor, Mr. Liudevit',
 'Simonius-Blumer, Col. Oberst Alfons',
 'Stanley, Miss. Amy Zillah Elsie',
 'Kalvik, Mr. Johannes Halvorsen',
 'Hickman, Mr. Leonard Mark',
 'Bourke, Mrs. John (Catherine)',
 'Eitemiller, Mr. George Floyd',
 'Newell, Mr. Arthur Webster',
 'Frauenthal, Dr. Henry William',
 'Badt, Mr. Mohamed',
 'Colley, Mr. Edward Pomeroy',
 'Coleff, Mr. Peju',
 'Lindqvist, Mr. Eino William',
 'Hickman, Mr. Lewis',
 'Butler, Mr. Reginald Fenton',
 'Cook, Mr. Jacob',
 'Brown, Mrs. Thomas William Solomon (Elizabeth Catherine Ford)',
 'Davidson, Mr. Thornton',
 'Mitchell, Mr. Henry Michael',
 'Wilhelms, Mr. Charles',
 'Sawyer, Mr. Frederick Charles',
 'Goodwin, Mrs. Frederick (Augusta Tyler)',
 'Cardeza, Mr. Thomas Drake Martinez',
 'Hassab, Mr. Hammad',
 'Olsvigen, Mr. Thor Anderson',
 'Brown, Mr. Thomas William Solomon',
 'Laroche, Mr. Joseph Philippe Lemercier',
 'Dakic, Mr. Branko',
 'Dick, Mr. Albert Adrian',
 'Saad, Mr. Khalil',
 'Weir, Col. John',
 'Chapman, Mr. Charles Henry',
 'Kelly, Mr. James',
 'Thayer, Mr. John Borland',
 'Humblen, Mr. Adolf Mathias Nicolai Olsen',
 'Silverthorne, Mr. Spencer Victor',
 'Gallagher, Mr. Martin',
 'Hansen, Mr. Henrik Juul',
 'Morley, Mr. Henry Samuel ("Mr Henry Marshall")',
 'Kelly, Mrs. Florence "Fannie"',
 'Calderhead, Mr. Edward Pennington',
 'Cleaver, Miss. Alice',
 'Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")',
 'Taylor, Mr. Elmer Zebley',
 'Larsson, Mr. August Viktor',
 'Greenberg, Mr. Samuel',
 'Soholt, Mr. Peter Andreas Lauritz Andersen',
 'Endres, Miss. Caroline Louise',
 'Troutt, Miss. Edwina Celia "Winnie"',
 'Johnson, Mr. Malkolm Joackim',
 'Gillespie, Mr. William Henry',
 'Hodges, Mr. Henry Price',
 'Chambers, Mr. Norman Campbell',
 'Oreskovic, Mr. Luka',
 'Renouf, Mrs. Peter Henry (Lillian Jefferys)',
 'Bryhl, Mr. Kurt Arnold Gottfrid',
 'Ilmakangas, Miss. Pieta Sofia',
 'Allen, Miss. Elisabeth Walton',
 'Berriman, Mr. William John',
 'Troupiansky, Mr. Moses Aaron',
 'Williams, Mr. Leslie',
 'Ford, Mrs. Edward (Margaret Ann Watson)',
 'Lesurer, Mr. Gustave J',
 'Cavendish, Mr. Tyrell William',
 'Ryerson, Miss. Susan Parker "Suzette"',
 'McNamee, Mr. Neal',
 'Stranden, Mr. Juho',
 'Crosby, Capt. Edward Gifford',
 'Sinkkonen, Miss. Anna',
 'Marvin, Mr. Daniel Warner',
 'Connaghton, Mr. Michael',
 'Vande Velde, Mr. Johannes Joseph',
 'Jonkoff, Mr. Lalio',
 'Herman, Mrs. Samuel (Jane Laver)',
 'Carlsson, Mr. August Sigfrid',
 'Theobald, Mr. Thomas Leonard',
 'Rothes, the Countess. of (Lucy Noel Martha Dyer-Edwards)',
 'Nirva, Mr. Iisakki Antino Aijo',
 'Barah, Mr. Hanna Assi',
 'Carter, Mrs. William Ernest (Lucile Polk)',
 'Hogeboom, Mrs. John C (Anna Andrews)',
 'Mangan, Miss. Mary',
 'Gronnestad, Mr. Daniel Danielsen',
 'Lievens, Mr. Rene Aime',
 'Jensen, Mr. Niels Peder',
 'Mack, Mrs. (Mary)',
 'Hocking, Mrs. Elizabeth (Eliza Needs)',
 'Robert, Mrs. Edward Scott (Elisabeth Walton McMillan)',
 'Long, Mr. Milton Clyde',
 'Ali, Mr. William',
 'Harmer, Mr. Abraham (David Lishin)',
 'Guggenheim, Mr. Benjamin',
 'Dantcheff, Mr. Ristiu',
 'Otter, Mr. Richard',
 'Leader, Dr. Alice (Farnham)',
 'Osman, Mrs. Mara',
 'Ibrahim Shawah, Mr. Yousseff',
 'Van Impe, Mrs. Jean Baptiste (Rosalie Paula Govaert)',
 'Ponesell, Mr. Martin',
 'Collyer, Mrs. Harvey (Charlotte Annie Tate)',
 'Hedman, Mr. Oskar Arvid',
 'Johansson, Mr. Karl Johan',
 'Andrews, Mr. Thomas Jr',
 'Meyer, Mr. August',
 'Chambers, Mrs. Norman Campbell (Bertha Griggs)',
 'Alexander, Mr. William',
 'Lester, Mr. James',
 'Slemen, Mr. Richard James',
 'Tomlin, Mr. Ernest Portage',
 'Heininen, Miss. Wendla Maria',
 'Mallet, Mr. Albert',
 'Holm, Mr. John Fredrik Alexander',
 'Hays, Mrs. Charles Melville (Clara Jennings Gregg)',
 'Lulic, Mr. Nikola',
 'Reuchlin, Jonkheer. John George',
 'Moor, Mrs. (Beila)',
 'Stone, Mrs. George Nelson (Martha Evelyn)',
 'Augustsson, Mr. Albert',
 'Compton, Miss. Sara Rebecca',
 'Pasic, Mr. Jakob',
 'Chip, Mr. Chang',
 'Alhomaki, Mr. Ilmari Rudolf',
 'Serepeca, Miss. Augusta',
 'Lemberopolous, Mr. Peter L',
 'Abbing, Mr. Anthony',
 'Markoff, Mr. Marin',
 'Harper, Rev. John',
 'Svensson, Mr. Johan',
 'Carter, Mrs. Ernest Courtenay (Lilian Hughes)',
 'Wick, Mrs. George Dennick (Mary Hitchcock)',
 'Daly, Mr. Peter Denis ',
 'Baclini, Mrs. Solomon (Latifa Qurban)',
 'Hansen, Mr. Claus Peter',
 'Giles, Mr. Frederick Edward',
 'Swift, Mrs. Frederick Joel (Margaret Welles Barron)',
 'Gill, Mr. John William',
 'Bystrom, Mrs. (Karolina)',
 'Duran y More, Miss. Asuncion',
 'Roebling, Mr. Washington Augustus II',
 'Balkic, Mr. Cerin',
 'Beckwith, Mrs. Richard Leonard (Sallie Monypeny)',
 'Carlsson, Mr. Frans Olof',
 'Vander Cruyssen, Mr. Victor',
 'Abelson, Mrs. Samuel (Hannah Wizosky)',
 'Gustafsson, Mr. Alfred Ossian',
 'Petroff, Mr. Nedelio',
 'Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)',
 'Shelley, Mrs. William (Imanita Parrish Hall)',
 'Markun, Mr. Johann',
 'Dahlberg, Miss. Gerda Ulrika',
 'Banfield, Mr. Frederick James',
 'Sutehall, Mr. Henry Jr',
 'Rice, Mrs. William (Margaret Norton)',
 'Montvila, Rev. Juozas',
 'Graham, Miss. Margaret Edith',
 'Behr, Mr. Karl Howell',
 'Dooley, Mr. Patrick']

In [165]:
len(df[df['Sex']=='male'])

577

In [167]:
len(df[df['Sex']=='female'])

314

In [159]:
len(df['Sex'])

891

In [169]:
df['Fare'].mean()

32.204207968574636

In [173]:
df[df['PassengerId']<32]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column,add,addition
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,100,new_join,1,"new_joinBraund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,S,100,new_join,1,"new_joinCumings, Mrs. John Bradley (Florence B..."
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,100,new_join,0,"new_joinHeikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,100,new_join,1,"new_joinFutrelle, Mrs. Jacques Heath (Lily May..."
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,100,new_join,0,"new_joinAllen, Mr. William Henry"
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,S,100,new_join,0,"new_joinMoran, Mr. James"
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,100,new_join,0,"new_joinMcCarthy, Mr. Timothy J"
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,100,new_join,4,"new_joinPalsson, Master. Gosta Leonard"
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,100,new_join,2,"new_joinJohnson, Mrs. Oscar W (Elisabeth Vilhe..."
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,S,100,new_join,1,"new_joinNasser, Mrs. Nicholas (Adele Achem)"
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,100,new_join,2,"new_joinSandstrom, Miss. Marguerite Rut"
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,100,new_join,0,"new_joinBonnell, Miss. Elizabeth"
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S,100,new_join,0,"new_joinSaundercock, Mr. William Henry"
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S,100,new_join,6,"new_joinAndersson, Mr. Anders Johan"
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S,100,new_join,0,"new_joinVestrom, Miss. Hulda Amanda Adolfina"
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,100,new_join,0,"new_joinHewlett, Mrs. (Mary D Kingcome)"
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,S,100,new_join,5,"new_joinRice, Master. Eugene"
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S,100,new_join,0,"new_joinWilliams, Mr. Charles Eugene"
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S,100,new_join,1,"new_joinVander Planke, Mrs. Julius (Emelia Mar..."
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,S,100,new_join,0,"new_joinMasselmani, Mrs. Fatima"
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S,100,new_join,0,"new_joinFynney, Mr. Joseph J"
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S,100,new_join,0,"new_joinBeesley, Mr. Lawrence"
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,S,100,new_join,0,"new_joinMcGowan, Miss. Anna ""Annie"""
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S,100,new_join,0,"new_joinSloper, Mr. William Thompson"
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S,100,new_join,4,"new_joinPalsson, Miss. Torborg Danira"
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S,100,new_join,6,"new_joinAsplund, Mrs. Carl Oscar (Selma August..."
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,S,100,new_join,0,"new_joinEmir, Mr. Farred Chehab"
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,100,new_join,5,"new_joinFortune, Mr. Charles Alexander"
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,S,100,new_join,0,"new_joinO'Dwyer, Miss. Ellen ""Nellie"""
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S,100,new_join,0,"new_joinTodoroff, Mr. Lalio"
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,S,100,new_join,0,"new_joinUruchurtu, Don. Manuel E"

In [177]:
len(df[df['Fare']<df['Fare'].mean()])

680

In [183]:
len(df[df['Fare']==0])

15

In [189]:
len(df[df['Sex']=='female'])

314

In [195]:
df['Sex'].value_counts(normalize=True)  #normalize gives precentage values

Sex
male      0.647587
female    0.352413
Name: proportion, dtype: float64

In [197]:
df[df['Pclass']==1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column,add,addition
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,S,100,new_join,1,"new_joinCumings, Mrs. John Bradley (Florence B..."
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,100,new_join,1,"new_joinFutrelle, Mrs. Jacques Heath (Lily May..."
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,100,new_join,0,"new_joinMcCarthy, Mr. Timothy J"
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,100,new_join,0,"new_joinBonnell, Miss. Elizabeth"
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S,100,new_join,0,"new_joinSloper, Mr. William Thompson"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,100,new_join,2,"new_joinBeckwith, Mrs. Richard Leonard (Sallie..."
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S,100,new_join,0,"new_joinCarlsson, Mr. Frans Olof"
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,S,100,new_join,1,"new_joinPotter, Mrs. Thomas Jr (Lily Alexenia ..."
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,100,new_join,0,"new_joinGraham, Miss. Margaret Edith"
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,S,100,new_join,0,"new_joinBehr, Mr. Karl Howell"

In [199]:
len(df[df['Pclass']==1])

216

In [203]:
df['Survived'].value_counts(normalize=True)

Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

In [211]:
 df[(df['Sex']=='female')& (df['Fare']>df['Fare'].mean())]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column,add,addition
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,S,100,new_join,1,"new_joinCumings, Mrs. John Bradley (Florence B..."
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,100,new_join,1,"new_joinFutrelle, Mrs. Jacques Heath (Lily May..."
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,S,100,new_join,1,"new_joinSpencer, Mrs. William Augustus (Marie ..."
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,NaN,S,100,new_join,3,"new_joinLaroche, Miss. Simonne Marie Anne Andree"
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,S,100,new_join,1,"new_joinHarper, Mrs. Henry Sleeper (Myna Haxtun)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,854,1,1,"Lines, Miss. Mary Conover",female,16.0,0,1,PC 17592,39.4000,D28,S,100,new_join,1,"new_joinLines, Miss. Mary Conover"
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S,100,new_join,2,"new_joinWick, Mrs. George Dennick (Mary Hitchc..."
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,100,new_join,10,"new_joinSage, Miss. Dorothy Edith ""Dolly"""
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,100,new_join,2,"new_joinBeckwith, Mrs. Richard Leonard (Sallie..."
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,S,100,new_join,1,"new_joinPotter, Mrs. Thomas Jr (Lily Alexenia ..."

In [213]:
import numpy as np

In [215]:
np.mean(df.Fare)

32.204207968574636

In [219]:
df.Fare.mean()

32.204207968574636

In [221]:
max(df.Fare)

512.3292

In [223]:
min(df.Fare)

0.0

In [227]:
df[df['Fare']==max(df.Fare)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column,add,addition
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,S,100,new_join,0,"new_joinWard, Miss. Anna"
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,S,100,new_join,1,"new_joinCardeza, Mr. Thomas Drake Martinez"
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,S,100,new_join,0,"new_joinLesurer, Mr. Gustave J"

In [231]:
df[df['Fare']== min(df.Fare)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column,add,addition
179,180,0,3,"Leonard, Mr. Lionel",male,36.0,0,0,LINE,0.0,NaN,S,100,new_join,0,"new_joinLeonard, Mr. Lionel"
263,264,0,1,"Harrison, Mr. William",male,40.0,0,0,112059,0.0,B94,S,100,new_join,0,"new_joinHarrison, Mr. William"
271,272,1,3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0,NaN,S,100,new_join,0,"new_joinTornquist, Mr. William Henry"
277,278,0,2,"Parkes, Mr. Francis ""Frank""",male,NaN,0,0,239853,0.0,NaN,S,100,new_join,0,"new_joinParkes, Mr. Francis ""Frank"""
302,303,0,3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,LINE,0.0,NaN,S,100,new_join,0,"new_joinJohnson, Mr. William Cahoone Jr"
413,414,0,2,"Cunningham, Mr. Alfred Fleming",male,NaN,0,0,239853,0.0,NaN,S,100,new_join,0,"new_joinCunningham, Mr. Alfred Fleming"
466,467,0,2,"Campbell, Mr. William",male,NaN,0,0,239853,0.0,NaN,S,100,new_join,0,"new_joinCampbell, Mr. William"
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0,NaN,S,100,new_join,0,"new_joinFrost, Mr. Anthony Wood ""Archie"""
597,598,0,3,"Johnson, Mr. Alfred",male,49.0,0,0,LINE,0.0,NaN,S,100,new_join,0,"new_joinJohnson, Mr. Alfred"
633,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0,NaN,S,100,new_join,0,"new_joinParr, Mr. William Henry Marsh"
674,675,0,2,"Watson, Mr. Ennis Hastings",male,NaN,0,0,239856,0.0,NaN,S,100,new_join,0,"new_joinWatson, Mr. Ennis Hastings"
732,733,0,2,"Knight, Mr. Robert J",male,NaN,0,0,239855,0.0,NaN,S,100,new_join,0,"new_joinKnight, Mr. Robert J"
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0,A36,S,100,new_join,0,"new_joinAndrews, Mr. Thomas Jr"
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0,B102,S,100,new_join,0,"new_joinFry, Mr. Richard"
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0,NaN,S,100,new_join,0,"new_joinReuchlin, Jonkheer. John George"

In [235]:
df[(df.Age <18) &( df['Survived']==1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column,add,addition
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,S,100,new_join,1,"new_joinNasser, Mrs. Nicholas (Adele Achem)"
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S,100,new_join,2,"new_joinSandstrom, Miss. Marguerite Rut"
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,S,100,new_join,0,"new_joinMcGowan, Miss. Anna ""Annie"""
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,S,100,new_join,1,"new_joinNicola-Yarred, Miss. Jamila"
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,S,100,new_join,3,"new_joinLaroche, Miss. Simonne Marie Anne Andree"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
830,831,1,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.00,1,0,2659,14.4542,NaN,S,100,new_join,1,"new_joinYasbeck, Mrs. Antoni (Selini Alexander)"
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S,100,new_join,2,"new_joinRichards, Master. George Sibley"
853,854,1,1,"Lines, Miss. Mary Conover",female,16.00,0,1,PC 17592,39.4000,D28,S,100,new_join,1,"new_joinLines, Miss. Mary Conover"
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S,100,new_join,2,"new_joinJohnson, Master. Harold Theodor"
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.00,0,0,2667,7.2250,NaN,S,100,new_join,0,"new_joinNajib, Miss. Adele Kiamie ""Jane"""

**#panda 2**

iloc indexing refer to integer,implicit indexing.loc indexinf reger to explicit indexing

In [241]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column,add,addition
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,100,new_join,1,"new_joinBraund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,S,100,new_join,1,"new_joinCumings, Mrs. John Bradley (Florence B..."
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,100,new_join,0,"new_joinHeikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,100,new_join,1,"new_joinFutrelle, Mrs. Jacques Heath (Lily May..."
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,100,new_join,0,"new_joinAllen, Mr. William Henry"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,100,new_join,0,"new_joinMontvila, Rev. Juozas"
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,100,new_join,0,"new_joinGraham, Miss. Margaret Edith"
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,100,new_join,3,"new_joinJohnston, Miss. Catherine Helen ""Carrie"""
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,S,100,new_join,0,"new_joinBehr, Mr. Karl Howell"
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,S,100,new_join,0,"new_joinDooley, Mr. Patrick"

In [245]:
df.loc[0:4]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column,add,addition
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,100,new_join,1,"new_joinBraund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,S,100,new_join,1,"new_joinCumings, Mrs. John Bradley (Florence B..."
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,100,new_join,0,"new_joinHeikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,100,new_join,1,"new_joinFutrelle, Mrs. Jacques Heath (Lily May..."
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,100,new_join,0,"new_joinAllen, Mr. William Henry"

In [247]:
df.iloc[0:4]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column,add,addition
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,100,new_join,1,"new_joinBraund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,S,100,new_join,1,"new_joinCumings, Mrs. John Bradley (Florence B..."
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,100,new_join,0,"new_joinHeikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,100,new_join,1,"new_joinFutrelle, Mrs. Jacques Heath (Lily May..."

In [251]:
df.iloc[0:3,['PassengerId','Pclass']]

IndexError: .iloc requires numeric indexers, got ['PassengerId' 'Pclass']

In [253]:
df.loc[0:2,['Survived','Age']]  #loc is a named indexing

   Survived   Age
0         0  22.0
1         1  38.0
2         1  26.0

In [255]:
df.iloc[0:3,[9,10]]

      Fare Cabin
0   7.2500   NaN
1  71.2833   C85
2   7.9250   NaN

In [261]:
df.iloc[0:3,5:7]

    Age  SibSp
0  22.0      1
1  38.0      1
2  26.0      0

In [263]:
df['Name'][3:5]

3    Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                        Allen, Mr. William Henry
Name: Name, dtype: object

In [267]:
list(df['Name'][6:8])

['McCarthy, Mr. Timothy J', 'Palsson, Master. Gosta Leonard']

In [279]:
pd.Series(df['Name'][4:7])

4    Allen, Mr. William Henry
5            Moran, Mr. James
6     McCarthy, Mr. Timothy J
Name: Name, dtype: object

In [301]:
s2=pd.Series(list(df['Name'][4:7]),index=['a','b','c'])

In [295]:
list(df['Name'][6:9])

['McCarthy, Mr. Timothy J',
 'Palsson, Master. Gosta Leonard',
 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)']

In [299]:
s=pd.Series(list(df['Name'][6:9]))

In [303]:
#in pd the dataframe and series are not concatinate

In [309]:
# onle when index are same the add in series

s=pd.Series(list(df['Name'][4:7]),index=['a','b','c'])

In [313]:
s1=pd.Series(list(df['Name'][9:12]),index=['a','b','c'])

In [315]:
s+s1

a    Allen, Mr. William HenryNasser, Mrs. Nicholas ...
b      Moran, Mr. JamesSandstrom, Miss. Marguerite Rut
c      McCarthy, Mr. Timothy JBonnell, Miss. Elizabeth
dtype: object

In [317]:
df.drop(['Pclass'],axis=1)

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column,add,addition
0,1,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,100,new_join,1,"new_joinBraund, Mr. Owen Harris"
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,S,100,new_join,1,"new_joinCumings, Mrs. John Bradley (Florence B..."
2,3,1,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,100,new_join,0,"new_joinHeikkinen, Miss. Laina"
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,100,new_join,1,"new_joinFutrelle, Mrs. Jacques Heath (Lily May..."
4,5,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,100,new_join,0,"new_joinAllen, Mr. William Henry"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,100,new_join,0,"new_joinMontvila, Rev. Juozas"
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,100,new_join,0,"new_joinGraham, Miss. Margaret Edith"
888,889,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,100,new_join,3,"new_joinJohnston, Miss. Catherine Helen ""Carrie"""
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,S,100,new_join,0,"new_joinBehr, Mr. Karl Howell"
890,891,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,S,100,new_join,0,"new_joinDooley, Mr. Patrick"

In [325]:
df.drop(['Pclass'],axis=1,inplace =True)

In [327]:
df

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column,add,addition
0,1,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,100,new_join,1,"new_joinBraund, Mr. Owen Harris"
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,S,100,new_join,1,"new_joinCumings, Mrs. John Bradley (Florence B..."
2,3,1,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,100,new_join,0,"new_joinHeikkinen, Miss. Laina"
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,100,new_join,1,"new_joinFutrelle, Mrs. Jacques Heath (Lily May..."
4,5,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,100,new_join,0,"new_joinAllen, Mr. William Henry"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,100,new_join,0,"new_joinMontvila, Rev. Juozas"
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,100,new_join,0,"new_joinGraham, Miss. Margaret Edith"
888,889,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,100,new_join,3,"new_joinJohnston, Miss. Catherine Helen ""Carrie"""
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,S,100,new_join,0,"new_joinBehr, Mr. Karl Howell"
890,891,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,S,100,new_join,0,"new_joinDooley, Mr. Patrick"

In [331]:
df.drop(4,axis=0,inplace=True)

In [335]:
df

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column,add,addition
0,1,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,100,new_join,1,"new_joinBraund, Mr. Owen Harris"
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,S,100,new_join,1,"new_joinCumings, Mrs. John Bradley (Florence B..."
2,3,1,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,100,new_join,0,"new_joinHeikkinen, Miss. Laina"
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,100,new_join,1,"new_joinFutrelle, Mrs. Jacques Heath (Lily May..."
5,6,0,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,S,100,new_join,0,"new_joinMoran, Mr. James"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,100,new_join,0,"new_joinMontvila, Rev. Juozas"
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,100,new_join,0,"new_joinGraham, Miss. Margaret Edith"
888,889,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,100,new_join,3,"new_joinJohnston, Miss. Catherine Helen ""Carrie"""
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,S,100,new_join,0,"new_joinBehr, Mr. Karl Howell"
890,891,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,S,100,new_join,0,"new_joinDooley, Mr. Patrick"

In [347]:
df.reset_index(drop=True)

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column,add,addition
0,1,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,100,new_join,1,"new_joinBraund, Mr. Owen Harris"
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,S,100,new_join,1,"new_joinCumings, Mrs. John Bradley (Florence B..."
2,3,1,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,100,new_join,0,"new_joinHeikkinen, Miss. Laina"
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,100,new_join,1,"new_joinFutrelle, Mrs. Jacques Heath (Lily May..."
4,6,0,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,S,100,new_join,0,"new_joinMoran, Mr. James"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,887,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,100,new_join,0,"new_joinMontvila, Rev. Juozas"
886,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,100,new_join,0,"new_joinGraham, Miss. Margaret Edith"
887,889,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,100,new_join,3,"new_joinJohnston, Miss. Catherine Helen ""Carrie"""
888,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,S,100,new_join,0,"new_joinBehr, Mr. Karl Howell"
889,891,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,S,100,new_join,0,"new_joinDooley, Mr. Patrick"

In [355]:
df.set_index(['Name'],inplace=True)

In [357]:
df

,PassengerId,Survived,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,death,new_column,add,addition
Name,,,,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,male,22.0,1,0,A/5 21171,7.2500,NaN,S,100,new_join,1,"new_joinBraund, Mr. Owen Harris"
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,female,38.0,1,0,PC 17599,71.2833,C85,S,100,new_join,1,"new_joinCumings, Mrs. John Bradley (Florence B..."
"Heikkinen, Miss. Laina",3,1,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,100,new_join,0,"new_joinHeikkinen, Miss. Laina"
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,female,35.0,1,0,113803,53.1000,C123,S,100,new_join,1,"new_joinFutrelle, Mrs. Jacques Heath (Lily May..."
"Moran, Mr. James",6,0,male,NaN,0,0,330877,8.4583,NaN,S,100,new_join,0,"new_joinMoran, Mr. James"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",887,0,male,27.0,0,0,211536,13.0000,NaN,S,100,new_join,0,"new_joinMontvila, Rev. Juozas"
"Graham, Miss. Margaret Edith",888,1,female,19.0,0,0,112053,30.0000,B42,S,100,new_join,0,"new_joinGraham, Miss. Margaret Edith"
"Johnston, Miss. Catherine Helen ""Carrie""",889,0,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,100,new_join,3,"new_joinJohnston, Miss. Catherine Helen ""Carrie"""
"Behr, Mr. Karl Howell",890,1,male,26.0,0,0,111369,30.0000,C148,S,100,new_join,0,"new_joinBehr, Mr. Karl Howell"
"Dooley, Mr. Patrick",891,0,male,32.0,0,0,370376,7.7500,NaN,S,100,new_join,0,"new_joinDooley, Mr. Patrick"

In [371]:
df.loc['Braund, Mr. Owen Harris']

PassengerId                                  1
Survived                                     0
Sex                                       male
Age                                       22.0
SibSp                                        1
Parch                                        0
Ticket                               A/5 21171
Fare                                      7.25
Cabin                                      NaN
Embarked                                     S
death                                      100
new_column                            new_join
add                                          1
addition       new_joinBraund, Mr. Owen Harris
Name: Braund, Mr. Owen Harris, dtype: object

In [377]:
df.reset_index(inplace=True)

In [391]:
d={'key1': [1,2,3,4],
                'key2':[23,45,89,60],
             'key3': [19.45,90,45,23]}

In [393]:
pd.DataFrame(d)

   key1  key2   key3
0     1    23  19.45
1     2    45  90.00
2     3    89  45.00
3     4    60  23.00

In [397]:
d={'key1':(12,89,56,34),
   'key2':(78,26,912,10),
   'key3':(12,79,54,61)}

In [403]:
pd.DataFrame(d)

   key1  key2  key3
0    12    78    12
1    89    26    79
2    56   912    54
3    34    10    61

In [409]:
 df=pd.read_csv("taxonomy.csv")

In [411]:
df.describe()

       taxonomy_id          name  parent_id       parent_name
count          290           290        279               279
unique         290           183         60                50
top            101  Nursing Home  106-06-07  Health Education
freq             1             4         11                15

In [413]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290 entries, 0 to 289
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   taxonomy_id  290 non-null    object
 1   name         290 non-null    object
 2   parent_id    279 non-null    object
 3   parent_name  279 non-null    object
dtypes: object(4)
memory usage: 9.2+ KB

In [433]:
df

    taxonomy_id                          name parent_id           parent_name
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
5     101-02-03          Help Pay for Housing    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[279 rows x 4 columns]

In [435]:
df.isnull().sum()

taxonomy_id    0
name           0
parent_id      0
parent_name    0
dtype: int64

In [437]:
df.dropna()

    taxonomy_id                          name parent_id           parent_name
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
5     101-02-03          Help Pay for Housing    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[279 rows x 4 columns]

In [439]:
df.dropna()

    taxonomy_id                          name parent_id           parent_name
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
5     101-02-03          Help Pay for Housing    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[279 rows x 4 columns]

In [455]:
df.dropna()

    taxonomy_id                          name parent_id           parent_name
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
5     101-02-03          Help Pay for Housing    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[279 rows x 4 columns]

In [457]:
df.isnull().sum()

taxonomy_id    0
name           0
parent_id      0
parent_name    0
dtype: int64

In [459]:
df.dropna(axis=1)

    taxonomy_id                          name parent_id           parent_name
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
5     101-02-03          Help Pay for Housing    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[279 rows x 4 columns]

In [463]:
df.isnull().sum()

taxonomy_id    0
name           0
parent_id      0
parent_name    0
dtype: int64

In [465]:
df[['parent_id']].dropna()

    parent_id
1         101
2         101
3      101-02
4      101-02
5      101-02
..        ...
285    111-01
286       111
287       111
288       111
289       111

[279 rows x 1 columns]

In [467]:
df[['parent_id','name']].dropna()

    parent_id                          name
1         101             Disaster Response
2         101                Emergency Cash
3      101-02             Help Pay for Food
4      101-02       Help Pay for Healthcare
5      101-02          Help Pay for Housing
..        ...                           ...
285    111-01              Workplace Rights
286       111                     Mediation
287       111                        Notary
288       111                Representation
289       111  Translation & Interpretation

[279 rows x 2 columns]

In [469]:
df.fillna('Null')

    taxonomy_id                          name parent_id           parent_name
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
5     101-02-03          Help Pay for Housing    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[279 rows x 4 columns]

In [471]:
df

    taxonomy_id                          name parent_id           parent_name
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
5     101-02-03          Help Pay for Housing    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[279 rows x 4 columns]

In [473]:
df.reset_index()

,index,taxonomy_id,name,parent_id,parent_name
0,1,101-01,Disaster Response,101,Emergency
1,2,101-02,Emergency Cash,101,Emergency
2,3,101-02-01,Help Pay for Food,101-02,Emergency Cash
3,4,101-02-02,Help Pay for Healthcare,101-02,Emergency Cash
4,5,101-02-03,Help Pay for Housing,101-02,Emergency Cash
...,...,...,...,...,...
274,285,111-01-07,Workplace Rights,111-01,Advocacy & Legal Aid
275,286,111-02,Mediation,111,Legal
276,287,111-03,Notary,111,Legal
277,288,111-04,Representation,111,Legal
278,289,111-05,Translation & Interpretation,111,Legal

In [475]:
df=pd.read_csv('taxonomy.csv')

In [477]:
df

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [479]:
df.fillna('Null')

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency      Null                  Null
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [481]:
df.fillna(0)

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency         0                     0
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [484]:
data1 = {
    'A': [1, 2, None, 4, 5, None, 7, 8, 9, 10],
    'B': [None, 11, 12, 13, None, 15, 16, None, 18, 19]
}

df2 = pd.DataFrame(data1)
df2

      A     B
0   1.0   NaN
1   2.0  11.0
2   NaN  12.0
3   4.0  13.0
4   5.0   NaN
5   NaN  15.0
6   7.0  16.0
7   8.0   NaN
8   9.0  18.0
9  10.0  19.0

In [488]:
df2.A.fillna(df2['A'].mean())

0     1.00
1     2.00
2     5.75
3     4.00
4     5.00
5     5.75
6     7.00
7     8.00
8     9.00
9    10.00
Name: A, dtype: float64

In [490]:
df2.fillna(df2.median())

      A     B
0   1.0  15.0
1   2.0  11.0
2   6.0  12.0
3   4.0  13.0
4   5.0  15.0
5   6.0  15.0
6   7.0  16.0
7   8.0  15.0
8   9.0  18.0
9  10.0  19.0

In [492]:
df2.fillna("some")

      A     B
0   1.0  some
1   2.0  11.0
2  some  12.0
3   4.0  13.0
4   5.0  some
5  some  15.0
6   7.0  16.0
7   8.0  some
8   9.0  18.0
9  10.0  19.0

In [496]:
df2.fillna(method='ffill')# bottom to top

C:\Users\mohda\AppData\Local\Temp\ipykernel_55076\2637084966.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method='ffill')

      A     B
0   1.0   NaN
1   2.0  11.0
2   2.0  12.0
3   4.0  13.0
4   5.0  13.0
5   5.0  15.0
6   7.0  16.0
7   8.0  16.0
8   9.0  18.0
9  10.0  19.0

In [498]:
df2.fillna(method='bfill')  #top to bottom

C:\Users\mohda\AppData\Local\Temp\ipykernel_55076\2667140817.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method='bfill')

      A     B
0   1.0  11.0
1   2.0  11.0
2   4.0  12.0
3   4.0  13.0
4   5.0  15.0
5   7.0  15.0
6   7.0  16.0
7   8.0  18.0
8   9.0  18.0
9  10.0  19.0

In [506]:
df2.median()

A     6.0
B    15.0
dtype: float64

In [508]:
df2.mode()

      A     B
0   1.0  11.0
1   2.0  12.0
2   4.0  13.0
3   5.0  15.0
4   7.0  16.0
5   8.0  18.0
6   9.0  19.0
7  10.0   NaN

In [510]:
df2.mean()

A     5.750000
B    14.857143
dtype: float64

In [512]:
df2.A.describe()

count     8.000000
mean      5.750000
std       3.284161
min       1.000000
25%       3.500000
50%       6.000000
75%       8.250000
max      10.000000
Name: A, dtype: float64

In [514]:
df3=pd.read_csv(r"C:\Users\mohda\Downloads\titanic (1).csv")

In [516]:
df3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [528]:
df3[df3.Survived==1]['Fare'].mean()

48.39540760233918

In [530]:
df3[df3.Survived==0]['Fare'].mean()

22.117886885245902

In [534]:
df3.groupby('Survived').mean(numeric_only=True)

          PassengerId    Pclass        Age     SibSp     Parch       Fare
Survived
0          447.016393  2.531876  30.626179  0.553734  0.329690  22.117887
1          444.368421  1.950292  28.343690  0.473684  0.464912  48.395408

In [538]:
df3.groupby('Survived').min(numeric_only=True)

          PassengerId  Pclass   Age  SibSp  Parch  Fare
Survived
0                   1       1  1.00      0      0   0.0
1                   2       1  0.42      0      0   0.0

In [542]:
df3.groupby(['Survived']).describe()

         PassengerId                                                     \
               count        mean         std  min     25%    50%    75%
Survived
0              549.0  447.016393  260.640469  1.0  211.00  455.0  675.0
1              342.0  444.368421  252.358840  2.0  250.75  439.5  651.5

                Pclass            ... Parch        Fare                        \
            max  count      mean  ...   75%  max  count       mean        std
Survived                          ...
0         891.0  549.0  2.531876  ...   0.0  6.0  549.0  22.117887  31.388207
1         890.0  342.0  1.950292  ...   1.0  5.0  342.0  48.395408  66.596998


          min      25%   50%   75%       max
Survived
0         0.0   7.8542  10.5  26.0  263.0000
1         0.0  12.4750  26.0  57.0  512.3292

[2 rows x 48 columns]

In [554]:
import numpy as np
df3.groupby('Survived')['Fare'].agg(['mean','median','count','std','var'])

               mean  median  count        std          var
Survived
0         22.117887    10.5    549  31.388207   985.219509
1         48.395408    26.0    342  66.596998  4435.160158

In [556]:
df3.groupby(['Sex','Pclass'])['Survived'].sum()

Sex     Pclass
female  1         91
        2         70
        3         72
male    1         45
        2         17
        3         47
Name: Survived, dtype: int64

In [560]:
df3.groupby(['Sex','Pclass'])['Survived'].sum().to_frame()

               Survived
Sex    Pclass
female 1             91
       2             70
       3             72
male   1             45
       2             17
       3             47

In [568]:
df3.groupby(['Pclass','Age'])['Survived'].sum().unstack

<bound method Series.unstack of Pclass  Age
1       0.92     1
        2.00     0
        4.00     1
        11.00    1
        14.00    1
                ..
3       61.00    0
        63.00    1
        65.00    0
        70.50    0
        74.00    0
Name: Survived, Length: 182, dtype: int64>

In [574]:
a=df3.groupby(['Pclass','Age'])['Survived'].sum().to_frame()

In [578]:
a.transpose()

Pclass       1                                                        ...  \
Age      0.92  2.00  4.00  11.00 14.00 15.00 16.00 17.00 18.00 19.00  ...
Survived     1     0     1     1     1     1     3     3     3     3  ...

Pclass       3
Age      49.00 50.00 51.00 55.50 59.00 61.00 63.00 65.00 70.50 74.00
Survived     0     0     0     0     0     0     1     0     0     0

[1 rows x 182 columns]

In [580]:
a.T

Pclass       1                                                        ...  \
Age      0.92  2.00  4.00  11.00 14.00 15.00 16.00 17.00 18.00 19.00  ...
Survived     1     0     1     1     1     1     3     3     3     3  ...

Pclass       3
Age      49.00 50.00 51.00 55.50 59.00 61.00 63.00 65.00 70.50 74.00
Survived     0     0     0     0     0     0     1     0     0     0

[1 rows x 182 columns]

In [582]:
df4=pd.read_csv(r"C:\Users\mohda\Downloads\titanic (1).csv")

In [584]:
df4

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [590]:
df1=df4[['Name','Sex','Age']][0:5]

In [592]:
df2=df4[['Name','Sex','Age']][5:10]

In [596]:
pd.concat([df1,df2])

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0
5                                   Moran, Mr. James    male   NaN
6                            McCarthy, Mr. Timothy J    male  54.0
7                     Palsson, Master. Gosta Leonard    male   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

In [598]:
pd.concat([df1,df2],axis=1)

,Name,Sex,Age,Name,Sex,Age
0,"Braund, Mr. Owen Harris",male,22.0,NaN,NaN,NaN
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,NaN,NaN,NaN
2,"Heikkinen, Miss. Laina",female,26.0,NaN,NaN,NaN
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,NaN,NaN,NaN
4,"Allen, Mr. William Henry",male,35.0,NaN,NaN,NaN
5,NaN,NaN,NaN,"Moran, Mr. James",male,NaN
6,NaN,NaN,NaN,"McCarthy, Mr. Timothy J",male,54.0
7,NaN,NaN,NaN,"Palsson, Master. Gosta Leonard",male,2.0
8,NaN,NaN,NaN,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0
9,NaN,NaN,NaN,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0

In [602]:
df1=df4[['Name','Age','Sex']][0:5]

In [604]:
df2=df4[['Name','Age','Sex']][5:10]

In [614]:
df2.reset_index(drop=True,inplace=True)

In [616]:
pd.concat([df1,df2],axis=1)

,Name,Age,Sex,Name,Age,Sex
0,"Braund, Mr. Owen Harris",22.0,male,"Moran, Mr. James",NaN,male
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,female,"McCarthy, Mr. Timothy J",54.0,male
2,"Heikkinen, Miss. Laina",26.0,female,"Palsson, Master. Gosta Leonard",2.0,male
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,female,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",27.0,female
4,"Allen, Mr. William Henry",35.0,male,"Nasser, Mrs. Nicholas (Adele Achem)",14.0,female

In [7]:
df2 =  pd.DataFrame({'key1':[1,2,45,6,67],
                      'key4':[56,5,6,7,8],
                      'key5':[3,56,5,6,6]
}
)

In [9]:
df2

   key1  key4  key5
0     1    56     3
1     2     5    56
2    45     6     5
3     6     7     6
4    67     8     6

In [11]:
df1 = pd.DataFrame({'key1':[1,2,4,5,6],
                      'key2':[4,5,6,7,8],
                      'key3':[3,4,5,6,6]
})

In [13]:
df1

   key1  key2  key3
0     1     4     3
1     2     5     4
2     4     6     5
3     5     7     6
4     6     8     6

In [15]:
df2 =  pd.DataFrame({'key1':[1,2,45,6,67],
                      'key4':[56,5,6,7,8],
                      'key5':[3,56,5,6,6]
}
)

In [17]:
df2

   key1  key4  key5
0     1    56     3
1     2     5    56
2    45     6     5
3     6     7     6
4    67     8     6

In [19]:
import pandas as pd

In [23]:
pd.merge(df1,df2,how='inner')

   key1  key2  key3  key4  key5
0     1     4     3    56     3
1     2     5     4     5    56
2     6     8     6     7     6